name: Merging Rules
on:
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master, develop]

permissions:
   contents: write
   pull-requests: write

jobs:
   dependabot:
      name: Dependabot Approve PRs and Merge
      runs-on: ubuntu-latest
      needs: e2e-tests
      if: ${{ github.actor == 'dependabot[bot]' }}
      strategy:
         matrix:
            package: ["@digiserve/ab-utils"]
      steps:
         - name: Dependabot metadata
           id: metadata
           uses: dependabot/fetch-metadata@v1
           with:
              github-token: "${{ secrets.GITHUB_TOKEN }}"
         - name: Approve a PR
           id: approve
           if: ${{ contains(steps.metadata.outputs.dependency-names, matrix.package) }}
           run: gh pr review --approve "$PR_URL" && echo "isapprove=1" >> $GITHUB_OUTPUT
           env:
              PR_URL: ${{github.event.pull_request.html_url}}
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         - name: Authenticate cli with a PAT
           run: echo "${{ secrets.DEPENDABOT_TOKEN }}" | gh auth login --with-token
         - name: Enable auto-merge for Dependabot PRs
           if: steps.approve.outputs.isapprove == '1'
           run: gh pr merge --auto --merge "$PR_URL"
           env:
              PR_URL: ${{github.event.pull_request.html_url}}
